# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            GeoSn0w
tagline:          'Programmer. Building and breaking things. Mostly breaking...'
description:      ''
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
